### ISSUE TITLE
mediatek u-boot

### ISSUE THREAD

**Issue by stpf99** [manjaro-pinephone/arm-profiles#6]
Hi
If it is possible to add support for some older not usable as some time ago smartphones i want to help, firstly if it is currently possible i want to try add support for my "Bluboo Xfire2" , this phone have mediatek mt6580 coretex a7 SoC (MediaTek MT6580 1.30 GHz x 4, GPU: ARM Mali-400 MP2 500 MHz) , If some branch have u-boot support for this device/SoC , in current official u-boot source tree is directory for mediatek but mt6580 is by now not listed.
i have unpacked original rom and u-boot is probably in preloader_magc6580_we_l.bin or lk.bin file but i don't know it is enough and how to integrate this blob in sources , maybe something like repository for u-boot files not open sourced but needed to booting wide range of hardware on opensource operating systems should be established and any system where is needed can have access to that repository... 

edit: 
is this is something needed in linux based os https://github.com/TheMuppets

**Comment by Strit** [comment]
The mt6580 SoC is only armv7h, which Manjaro ARM has not supported for a couple of years.

So sorry, but no. Manjaro will not support this SoC.
Try with Arch Linux ARM, as they still support armv7h architecture.
